services:
  npr_main:
    build: ./npr_main
    container_name: npr_main
    ports:
      - "8000:8000"
    volumes:
      - ./NPR_Main:/app
    restart: unless-stopped

  npr_app:
    build: ./npr_app
    container_name: npr_app
    ports:
      - "8501:8501"
    volumes:
      - ./NPR_app:/app
    depends_on:
      - npr_main
    restart: unless-stopped